server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoelMaciel/ead_config-server-repo
          default-label: main
          username: JoelMaciel
          password: ${ACCESS_TOKEN}

ead:
  configServer:
    username: ${NAME_CONFIG}
    password: ${PASSWORD_CONFIG}
  serviceRegistry:
    username: ${NAME}
    password: ${PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost